package com.vibecheck.app.ui.friendship

data class Country(
    val name: String,
    val code: String,
    val dialCode: String,
    val flag: String,
)

val COUNTRIES = listOf(
    Country("United States", "US", "+1", "🇺🇸"),
    Country("United Kingdom", "GB", "+44", "🇬🇧"),
    Country("Canada", "CA", "+1", "🇨🇦"),
    Country("Australia", "AU", "+61", "🇦🇺"),
    Country("India", "IN", "+91", "🇮🇳"),
    Country("Germany", "DE", "+49", "🇩🇪"),
    Country("France", "FR", "+33", "🇫🇷"),
    Country("Spain", "ES", "+34", "🇪🇸"),
    Country("Italy", "IT", "+39", "🇮🇹"),
    Country("Japan", "JP", "+81", "🇯🇵"),
    Country("China", "CN", "+86", "🇨🇳"),
    Country("Brazil", "BR", "+55", "🇧🇷"),
    Country("Mexico", "MX", "+52", "🇲🇽"),
    Country("South Korea", "KR", "+82", "🇰🇷"),
    Country("Russia", "RU", "+7", "🇷🇺"),
    Country("Netherlands", "NL", "+31", "🇳🇱"),
    Country("Belgium", "BE", "+32", "🇧🇪"),
    Country("Sweden", "SE", "+46", "🇸🇪"),
    Country("Norway", "NO", "+47", "🇳🇴"),
    Country("Denmark", "DK", "+45", "🇩🇰"),
    Country("Switzerland", "CH", "+41", "🇨🇭"),
    Country("Austria", "AT", "+43", "🇦🇹"),
    Country("Poland", "PL", "+48", "🇵🇱"),
    Country("Greece", "GR", "+30", "🇬🇷"),
    Country("Portugal", "PT", "+351", "🇵🇹"),
    Country("Ireland", "IE", "+353", "🇮🇪"),
    Country("New Zealand", "NZ", "+64", "🇳🇿"),
    Country("Singapore", "SG", "+65", "🇸🇬"),
    Country("Malaysia", "MY", "+60", "🇲🇾"),
    Country("Thailand", "TH", "+66", "🇹🇭"),
    Country("Philippines", "PH", "+63", "🇵🇭"),
    Country("Indonesia", "ID", "+62", "🇮🇩"),
    Country("Vietnam", "VN", "+84", "🇻🇳"),
    Country("Pakistan", "PK", "+92", "🇵🇰"),
    Country("Bangladesh", "BD", "+880", "🇧🇩"),
    Country("Sri Lanka", "LK", "+94", "🇱🇰"),
    Country("South Africa", "ZA", "+27", "🇿🇦"),
    Country("Egypt", "EG", "+20", "🇪🇬"),
    Country("Nigeria", "NG", "+234", "🇳🇬"),
    Country("Kenya", "KE", "+254", "🇰🇪"),
    Country("Argentina", "AR", "+54", "🇦🇷"),
    Country("Chile", "CL", "+56", "🇨🇱"),
    Country("Colombia", "CO", "+57", "🇨🇴"),
    Country("Peru", "PE", "+51", "🇵🇪"),
    Country("Saudi Arabia", "SA", "+966", "🇸🇦"),
    Country("United Arab Emirates", "AE", "+971", "🇦🇪"),
    Country("Israel", "IL", "+972", "🇮🇱"),
    Country("Turkey", "TR", "+90", "🇹🇷"),
    Country("Thailand", "TH", "+66", "🇹🇭"),
    Country("Hong Kong", "HK", "+852", "🇭🇰"),
    Country("Taiwan", "TW", "+886", "🇹🇼"),
)
